import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DashboardWrapper from "./dashboardWrapper";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
  SignIn
} from '@clerk/nextjs';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className="main-container">
          <SignedOut>
            <div className="center-container">
                <SignIn routing="hash" />
              </div>
          </SignedOut>
          <SignedIn>
            <UserButton />
            <DashboardWrapper>{children}</DashboardWrapper>
          </SignedIn>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
